# Generated by Django 3.0.8 on 2020-10-07 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=24)),
                ('min_price', models.FloatField()),
                ('step_price', models.FloatField()),
                ('step_quantity', models.FloatField()),
                ('min_quantity', models.FloatField()),
                ('min_amount', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='market.Market')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
