# Generated by Django 3.0.8 on 2020-12-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='last_ticker_price',
            field=models.FloatField(default=0, help_text='This price may be a little outdated'),
        ),
    ]
