# Generated by Django 3.0.8 on 2020-10-07 11:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='unique name. Lowercase alphanumeric and underscores', max_length=50, unique=True)),
                ('abbr', models.CharField(help_text='unique short abbreviation for custom_order_id', max_length=6, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
