# Generated by Django 3.0.8 on 2020-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techannel',
            name='auto_bi_futures',
            field=models.BooleanField(default=False, help_text='Auto creating into Signal for BiFutures Market'),
        ),
        migrations.AddField(
            model_name='techannel',
            name='auto_bi_spot',
            field=models.BooleanField(default=False, help_text='Auto creating into Signal for BiSpot Market'),
        ),
    ]
