# Generated by Django 3.0.8 on 2020-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techannel',
            name='abbr',
            field=models.CharField(help_text='unique abbreviation', max_length=15, unique=True),
        ),
    ]
