# Generated by Django 3.0.8 on 2020-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0002_auto_20200928_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techannel',
            name='abbr',
            field=models.CharField(default='489b', help_text='unique short abbreviation for custom_order_id', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='techannel',
            name='name',
            field=models.CharField(help_text='unique name. Lowercase alphanumeric and underscores', max_length=50, unique=True),
        ),
    ]
