# Generated by Django 3.0.8 on 2020-12-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0002_auto_20201120_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='techannel',
            name='auto_trailing_stop',
            field=models.BooleanField(default=False, help_text='Auto add trailing_stop_enabled for new Signals. It works if one of the next flags is set: auto_bi_futures, auto_bi_spot'),
        ),
    ]
