# Generated by Django 3.0.8 on 2020-12-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0003_techannel_auto_trailing_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='techannel',
            name='balance_to_signal_perc',
            field=models.FloatField(default=3, help_text='percent for one signal from the balance'),
        ),
    ]
