# Generated by Django 3.0.8 on 2021-04-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0004_techannel_balance_to_signal_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='techannel',
            name='leverage_boost',
            field=models.PositiveIntegerField(default=0, help_text='The number to add to the recommended leverage'),
        ),
    ]
