# Generated by Django 3.0.8 on 2021-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0005_techannel_leverage_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='techannel',
            name='custom_stop_loss_perc',
            field=models.PositiveIntegerField(default=0, help_text='Own stop-loss value in % from average EP'),
        ),
    ]
