# Generated by Django 3.0.8 on 2021-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0006_techannel_custom_stop_loss_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techannel',
            name='custom_stop_loss_perc',
            field=models.FloatField(default=0, help_text='Own stop-loss value in % from average EP'),
        ),
    ]
