# Generated by Django 3.0.8 on 2020-09-10 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=16)),
                ('signal_id', models.PositiveIntegerField(unique=True)),
                ('main_coin', models.CharField(max_length=16)),
                ('stop_loss', models.FloatField()),
                ('_bought_quantity', models.FloatField(db_column='bought_quantity', default=0, help_text='Fullness of buy_orders')),
                ('income', models.FloatField(default=0, help_text='Profit or Loss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_profits', to='signal.Signal')),
            ],
            options={
                'unique_together': {('signal', 'value')},
            },
        ),
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='signal.Signal')),
            ],
            options={
                'unique_together': {('signal', 'value')},
            },
        ),
    ]
