# Generated by Django 3.0.8 on 2020-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='leverage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='signal',
            name='position',
            field=models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT')], default='long', max_length=32),
        ),
    ]
