# Generated by Django 3.0.8 on 2020-10-11 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='message_date',
            field=models.TimeField(default=django.utils.timezone.now, max_length=32),
        ),
    ]
