# Generated by Django 3.0.8 on 2020-10-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0002_signal_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='_status',
            field=models.CharField(choices=[('new', 'NEW'), ('formed', 'FORMED'), ('pushed', 'PUSHED'), ('bought', 'BOUGHT'), ('sold', 'SOLD'), ('canceling', 'CANCELING'), ('closed', 'CLOSED')], db_column='status', default='new', max_length=32),
        ),
    ]
