# Generated by Django 3.0.8 on 2020-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0002_auto_20201002_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='position',
            field=models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT'), ('error', 'ERROR')], default='long', max_length=32),
        ),
    ]
