# Generated by Django 3.0.8 on 2020-10-12 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0003_auto_20201011_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='message_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
