# Generated by Django 3.0.8 on 2020-10-13 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0004_auto_20201012_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='all_targets',
            field=models.BooleanField(default=True, help_text='Flag is unset if the Signal was spoiled by admin'),
        ),
        migrations.CreateModel(
            name='HistorySignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('formed', 'FORMED'), ('pushed', 'PUSHED'), ('bought', 'BOUGHT'), ('sold', 'SOLD'), ('canceling', 'CANCELING'), ('closed', 'CLOSED')], default='new', max_length=32)),
                ('current_price', models.FloatField(null=True)),
                ('main_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_history', to='signal.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
