# Generated by Django 3.0.8 on 2020-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0005_auto_20201013_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='_bought_quantity',
        ),
        migrations.AddField(
            model_name='signal',
            name='amount',
            field=models.FloatField(default=0, help_text='Amount of Main Asset'),
        ),
    ]
