# Generated by Django 3.0.8 on 2020-10-21 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('techannel', '0001_initial'),
        ('signal', '0006_auto_20201014_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalOrig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=24)),
                ('outer_signal_id', models.PositiveIntegerField()),
                ('main_coin', models.CharField(max_length=16)),
                ('stop_loss', models.FloatField()),
                ('position', models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT'), ('error', 'ERROR')], default='long', max_length=32)),
                ('leverage', models.PositiveIntegerField(default=1)),
                ('message_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('techannel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signals_orig', to='techannel.Techannel')),
            ],
            options={
                'unique_together': {('techannel', 'outer_signal_id')},
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='signals', to='market.Market'),
        ),
        migrations.AlterUniqueTogether(
            name='signal',
            unique_together={('techannel', 'outer_signal_id', 'market')},
        ),
        migrations.CreateModel(
            name='TakeProfitOrig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_profits', to='signal.SignalOrig')),
            ],
            options={
                'unique_together': {('signal', 'value')},
            },
        ),
        migrations.CreateModel(
            name='EntryPointOrig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='signal.SignalOrig')),
            ],
            options={
                'unique_together': {('signal', 'value')},
            },
        ),
    ]
