# Generated by Django 3.0.8 on 2020-10-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('signal', '0008_fill_signal_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signals', to='market.Market'),
        ),
    ]
