# Generated by Django 3.0.8 on 2020-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0009_auto_20201021_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='trailing_stop_enabled',
            field=models.BooleanField(default=False, help_text='Trail SL if price has become above near EP (LONG) or lower (SHORT)'),
        ),
    ]
