# Generated by Django 3.0.8 on 2020-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0010_signal_trailing_stop_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysignal',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('formed', 'FORMED'), ('pushed', 'PUSHED'), ('bought', 'BOUGHT'), ('sold', 'SOLD'), ('canceling', 'CANCELING'), ('closed', 'CLOSED'), ('error', 'ERROR')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='signal',
            name='_status',
            field=models.CharField(choices=[('new', 'NEW'), ('formed', 'FORMED'), ('pushed', 'PUSHED'), ('bought', 'BOUGHT'), ('sold', 'SOLD'), ('canceling', 'CANCELING'), ('closed', 'CLOSED'), ('error', 'ERROR')], db_column='status', default='new', max_length=32),
        ),
    ]
