# Generated by Django 3.0.8 on 2020-12-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0011_auto_20201211_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='all_targets',
            new_name='spoiled',
        ),
        migrations.AddField(
            model_name='signal',
            name='margin_type',
            field=models.CharField(default='ISOLATED', max_length=9),
        ),
        migrations.AddField(
            model_name='signalorig',
            name='margin_type',
            field=models.CharField(default='ISOLATED', max_length=9),
        ),
    ]
