# Generated by Django 3.0.8 on 2020-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0012_auto_20201216_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='margin_type',
            field=models.CharField(choices=[('ISOLATED', 'ISOLATED'), ('CROSSED', 'CROSSED')], default='ISOLATED', max_length=9),
        ),
        migrations.AlterField(
            model_name='signalorig',
            name='margin_type',
            field=models.CharField(choices=[('ISOLATED', 'ISOLATED'), ('CROSSED', 'CROSSED')], default='ISOLATED', max_length=9),
        ),
    ]
