# Generated by Django 3.0.8 on 2020-12-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0013_auto_20201217_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='spoiled',
            new_name='uninterrupted',
        ),
    ]
