# Generated by Django 3.0.8 on 2020-12-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0014_auto_20201217_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalorig',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
