# Generated by Django 3.0.8 on 2020-12-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0015_signalorig_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalorig',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
