# Generated by Django 3.0.8 on 2020-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0016_signalorig_is_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
