# Generated by Django 3.0.8 on 2021-01-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0017_signal_is_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='For transactional tasks'),
        ),
    ]
