# Generated by Django 3.0.8 on 2021-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0018_signal_is_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='is_busy',
        ),
        migrations.AddField(
            model_name='signal',
            name='busy_setting_time',
            field=models.DateTimeField(blank=True, help_text='For transactional tasks', null=True),
        ),
    ]
