# Generated by Django 3.0.8 on 2021-11-25 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techannel', '0007_auto_20210505_1027'),
        ('signal', '0019_auto_20210309_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descriptions', models.TextField()),
                ('symbol', models.CharField(max_length=24)),
                ('outer_signal_id', models.PositiveIntegerField()),
                ('main_coin', models.CharField(max_length=16)),
                ('stop_loss', models.FloatField()),
                ('position', models.CharField(choices=[('long', 'LONG'), ('short', 'SHORT'), ('error', 'ERROR')], default='long', max_length=32)),
                ('leverage', models.PositiveIntegerField(default=1)),
                ('margin_type', models.CharField(choices=[('ISOLATED', 'ISOLATED'), ('CROSSED', 'CROSSED')], default='ISOLATED', max_length=9)),
                ('message_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('techannel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signal_desc', to='techannel.Techannel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
