# Generated by Django 3.0.8 on 2021-11-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0020_signaldesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaldesc',
            name='stop_loss',
        ),
    ]
