# Generated by Django 3.0.8 on 2021-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0020_signaldesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaldesc',
            name='descriptions',
            field=models.TextField(max_length=100),
        ),
    ]
