# Generated by Django 3.0.8 on 2021-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0021_auto_20211124_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaldesc',
            name='descriptions',
            field=models.TextField(),
        ),
    ]
