# Generated by Django 3.0.8 on 2022-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0021_remove_signaldesc_stop_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='outer_signal_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signaldesc',
            name='outer_signal_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signalorig',
            name='outer_signal_id',
            field=models.IntegerField(),
        ),
    ]
