# Generated by Django 3.0.8 on 2020-09-22 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signal', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=16)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('local_canceled', models.BooleanField(default=False)),
                ('local_canceled_time', models.DateTimeField(blank=True, null=True)),
                ('no_need_push', models.BooleanField(default=False, help_text='No need push the order to the market')),
                ('last_updated_by_api', models.DateTimeField(blank=True, null=True)),
                ('bought_quantity', models.FloatField(default=0)),
                ('custom_order_id', models.CharField(max_length=30)),
                ('_status', models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('unknown', 'UNKNOWN')], db_column='status', default='not_sent', max_length=32)),
                ('index', models.PositiveIntegerField()),
                ('handled_worked', models.BooleanField(default=False, help_text='Did something if the order has worked')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_orders', to='market.Market')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_orders', to='signal.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=16)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('handled_worked', models.BooleanField(default=False, help_text='Did something if the order has worked')),
                ('local_canceled', models.BooleanField(default=False)),
                ('local_canceled_time', models.DateTimeField(blank=True, null=True)),
                ('no_need_push', models.BooleanField(default=False, help_text='No need push the order to the market')),
                ('last_updated_by_api', models.DateTimeField(blank=True, null=True)),
                ('stop_loss', models.FloatField(default=0)),
                ('sold_quantity', models.FloatField(default=0)),
                ('custom_order_id', models.CharField(max_length=30)),
                ('_status', models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('unknown', 'UNKNOWN')], db_column='status', default='not_sent', max_length=32)),
                ('index', models.PositiveIntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_orders', to='market.Market')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_orders', to='signal.Signal')),
                ('tp_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sl_order', to='order.SellOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryApiSellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('status', models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('unknown', 'UNKNOWN')], default='not_sent', max_length=32)),
                ('sold_quantity', models.FloatField(default=0)),
                ('main_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_history', to='order.SellOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryApiBuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('status', models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('unknown', 'UNKNOWN')], default='not_sent', max_length=32)),
                ('bought_quantity', models.FloatField(default=0)),
                ('main_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_history', to='order.BuyOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
