# Generated by Django 3.0.8 on 2020-09-10 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('signal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=16)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('sold_quantity', models.FloatField(default=0)),
                ('custom_order_id', models.CharField(max_length=30)),
                ('_status', models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('unknown', 'UNKNOWN')], db_column='status', default='not_sent', max_length=32)),
                ('index', models.PositiveIntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_orders', to='market.Market')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell_orders', to='signal.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(max_length=16)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('bought_quantity', models.FloatField(default=0)),
                ('custom_order_id', models.CharField(max_length=30)),
                ('_status', models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('unknown', 'UNKNOWN')], db_column='status', default='not_sent', max_length=32)),
                ('index', models.PositiveIntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_orders', to='market.Market')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_orders', to='signal.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
