# Generated by Django 3.0.8 on 2020-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='custom_order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='custom_order_id',
            field=models.CharField(max_length=50),
        ),
    ]
