# Generated by Django 3.0.8 on 2020-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='_status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('expired', 'EXPIRED'), ('unknown', 'UNKNOWN')], db_column='status', default='not_sent', max_length=32),
        ),
        migrations.AlterField(
            model_name='historyapibuyorder',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('expired', 'EXPIRED'), ('unknown', 'UNKNOWN')], default='not_sent', max_length=32),
        ),
        migrations.AlterField(
            model_name='historyapisellorder',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('expired', 'EXPIRED'), ('unknown', 'UNKNOWN')], default='not_sent', max_length=32),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='_status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('not_sent', 'NOT_SENT'), ('not_exists', 'NOT_EXISTS'), ('sent', 'SENT'), ('expired', 'EXPIRED'), ('unknown', 'UNKNOWN')], db_column='status', default='not_sent', max_length=32),
        ),
    ]
