# Generated by Django 3.0.8 on 2020-10-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201008_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET'), ('take_profit', 'TAKE_PROFIT'), ('stop_loss', 'STOP_LOSS'), ('stop_loss_limit', 'STOP_LOSS_LIMIT'), ('take_profit_limit', 'TAKE_PROFIT_LIMIT'), ('limit_maker', 'LIMIT_MAKER')], default='limit', max_length=32),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET'), ('take_profit', 'TAKE_PROFIT'), ('stop_loss', 'STOP_LOSS'), ('stop_loss_limit', 'STOP_LOSS_LIMIT'), ('take_profit_limit', 'TAKE_PROFIT_LIMIT'), ('limit_maker', 'LIMIT_MAKER')], default='limit', max_length=32),
        ),
    ]
