# Generated by Django 3.0.8 on 2020-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200925_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='custom_order_id',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='custom_order_id',
            field=models.CharField(max_length=55),
        ),
    ]
