# Generated by Django 3.0.8 on 2020-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201010_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='stop_loss',
            field=models.FloatField(default=0),
        ),
    ]
