# Generated by Django 3.0.8 on 2020-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200928_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='push_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='push_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
