# Generated by Django 3.0.8 on 2020-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200930_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='custom_order_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='custom_order_id',
            field=models.CharField(max_length=36),
        ),
    ]
