# Generated by Django 3.0.8 on 2020-11-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signal', '0009_auto_20201021_1223'),
        ('order', '0004_buyorder_stop_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to='signal.Signal'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET'), ('take_profit', 'TAKE_PROFIT'), ('stop_loss', 'STOP_LOSS'), ('stop_loss_limit', 'STOP_LOSS_LIMIT'), ('stop_market', 'STOP_MARKET'), ('take_profit_limit', 'TAKE_PROFIT_LIMIT'), ('limit_maker', 'LIMIT_MAKER')], default='limit', max_length=32),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to='signal.Signal'),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET'), ('take_profit', 'TAKE_PROFIT'), ('stop_loss', 'STOP_LOSS'), ('stop_loss_limit', 'STOP_LOSS_LIMIT'), ('stop_market', 'STOP_MARKET'), ('take_profit_limit', 'TAKE_PROFIT_LIMIT'), ('limit_maker', 'LIMIT_MAKER')], default='limit', max_length=32),
        ),
    ]
