# Generated by Django 3.0.8 on 2020-11-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201107_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyorder',
            old_name='stop_loss',
            new_name='trigger',
        ),
        migrations.RenameField(
            model_name='sellorder',
            old_name='stop_loss',
            new_name='trigger',
        ),
    ]
