# Generated by Django 3.0.8 on 2021-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201108_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='init_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historyapibuyorder',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historyapisellorder',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='init_price',
            field=models.FloatField(default=0),
        ),
    ]
