# Generated by Django 3.0.8 on 2022-06-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210212_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET'), ('take_profit', 'TAKE_PROFIT'), ('stop_loss', 'STOP_LOSS'), ('stop_loss_limit', 'STOP_LOSS_LIMIT'), ('stop_market', 'STOP_MARKET'), ('stop_limit', 'STOP_LIMIT'), ('take_profit_limit', 'TAKE_PROFIT_LIMIT'), ('limit_maker', 'LIMIT_MAKER')], default='limit', max_length=32),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('market', 'MARKET'), ('take_profit', 'TAKE_PROFIT'), ('stop_loss', 'STOP_LOSS'), ('stop_loss_limit', 'STOP_LOSS_LIMIT'), ('stop_market', 'STOP_MARKET'), ('stop_limit', 'STOP_LIMIT'), ('take_profit_limit', 'TAKE_PROFIT_LIMIT'), ('limit_maker', 'LIMIT_MAKER')], default='limit', max_length=32),
        ),
    ]
