# Generated by Django 3.0.8 on 2020-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_buy_orders_enabled', models.BooleanField(default=False)),
                ('push_job_enabled', models.BooleanField(default=False)),
                ('pull_job_enabled', models.BooleanField(default=False)),
                ('bought_worker_enabled', models.BooleanField(default=False)),
                ('sold_worker_enabled', models.BooleanField(default=False)),
                ('ai_algorithm', models.BooleanField(default=False)),
                ('crypto_passive', models.BooleanField(default=False)),
                ('assist_leverage', models.BooleanField(default=False)),
                ('assist_altcoin', models.BooleanField(default=False)),
                ('assist_origin', models.BooleanField(default=False)),
                ('margin_whale', models.BooleanField(default=False)),
                ('balance_to_signal_perc', models.FloatField(default=0, help_text='how percent for one signal from the balance')),
                ('slip_delta_sl_perc', models.FloatField(default=0.2, help_text='slip delta stop loss percentage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
