# Generated by Django 3.0.8 on 2020-09-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_buy_orders_enabled', models.BooleanField(default=False)),
                ('push_job_enabled', models.BooleanField(default=False)),
                ('pull_job_enabled', models.BooleanField(default=False)),
                ('bought_worker_enabled', models.BooleanField(default=False)),
                ('sold_worker_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
