# Generated by Django 3.0.8 on 2020-10-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='close_worker_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crontask',
            name='spoil_worker_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
