# Generated by Django 3.0.8 on 2020-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='china_channel_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crontask',
            name='crypto_channel_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crontask',
            name='tca_altcoin_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crontask',
            name='tca_leverage_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
