# Generated by Django 3.0.8 on 2020-11-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0002_auto_20201014_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='form_buy_orders_enabled',
            new_name='first_forming_enabled',
        ),
    ]
