# Generated by Django 3.0.8 on 2020-09-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0002_auto_20200929_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='tca_origin_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
