# Generated by Django 3.0.8 on 2020-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0003_crontask_tca_origin_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='balance_to_signal_perc',
            field=models.FloatField(default=0, help_text='how percent for one signal from the balance'),
        ),
        migrations.AddField(
            model_name='crontask',
            name='slip_delta_sl_perc',
            field=models.FloatField(default=0.2, help_text='slip delta stop loss percentage'),
        ),
    ]
