# Generated by Django 3.0.8 on 2020-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0003_auto_20201101_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='white_bull',
            field=models.BooleanField(default=False),
        ),
    ]
