# Generated by Django 3.0.8 on 2020-10-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0004_auto_20201001_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='china_channel_enabled',
            new_name='ai_algorithm',
        ),
        migrations.RenameField(
            model_name='crontask',
            old_name='tca_altcoin_enabled',
            new_name='assist_altcoin',
        ),
        migrations.RenameField(
            model_name='crontask',
            old_name='tca_leverage_enabled',
            new_name='assist_leverage',
        ),
        migrations.RenameField(
            model_name='crontask',
            old_name='tca_origin_enabled',
            new_name='assist_origin',
        ),
        migrations.RenameField(
            model_name='crontask',
            old_name='crypto_channel_enabled',
            new_name='crypto_passive',
        ),
    ]
