# Generated by Django 3.0.8 on 2020-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0004_crontask_white_bull'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='simple_future',
            field=models.BooleanField(default=False),
        ),
    ]
