# Generated by Django 3.0.8 on 2020-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0005_auto_20201002_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='margin_whale',
            field=models.BooleanField(default=False),
        ),
    ]
