# Generated by Django 3.0.8 on 2020-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0005_crontask_simple_future'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='lucrative_trend',
            field=models.BooleanField(default=False),
        ),
    ]
