# Generated by Django 3.0.8 on 2020-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0006_crontask_lucrative_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='raticoin',
            field=models.BooleanField(default=False),
        ),
    ]
