# Generated by Django 3.0.8 on 2020-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0007_crontask_raticoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='bull_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crontask',
            name='crypto_zone',
            field=models.BooleanField(default=False),
        ),
    ]
