# Generated by Django 3.0.8 on 2020-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0008_auto_20201121_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='wcse',
            field=models.BooleanField(default=False),
        ),
    ]
