# Generated by Django 3.0.8 on 2020-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0009_crontask_wcse'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='sell_residual_quantity_enabled',
            field=models.BooleanField(default=False, help_text='If enabled in Futures (close_worker) residual quantity will be sold (LONG) or bought (SHORT)'),
        ),
    ]
