# Generated by Django 3.0.8 on 2020-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0010_crontask_sell_residual_quantity_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='trailing_stop_enabled',
            field=models.BooleanField(default=False, help_text='Trail SL if price has become above near EP (LONG) or lower (SHORT)'),
        ),
    ]
