# Generated by Django 3.0.8 on 2020-12-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0011_crontask_trailing_stop_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='prices_update_worker_enabled',
            field=models.BooleanField(default=True, help_text='Allow price updates into the Pair table (prices_update_worker)'),
        ),
    ]
