# Generated by Django 3.0.8 on 2020-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0012_crontask_prices_update_worker_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='lucrative',
            field=models.BooleanField(default=False),
        ),
    ]
