# Generated by Django 3.0.8 on 2020-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0013_crontask_lucrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='server',
            field=models.BooleanField(default=False),
        ),
    ]
