# Generated by Django 3.0.8 on 2020-12-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0013_crontask_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='balance_to_signal_perc',
            field=models.FloatField(default=3, help_text='how percent for one signal from the balance'),
        ),
    ]
