# Generated by Django 3.0.8 on 2020-12-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0015_auto_20201215_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='lucrative_trend',
            new_name='lucrative_recommendations',
        ),
    ]
