# Generated by Django 3.0.8 on 2020-12-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0016_auto_20201221_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='klondike',
            field=models.BooleanField(default=False),
        ),
    ]
