# Generated by Django 3.0.8 on 2020-12-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0017_crontask_klondike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='lucrative',
            new_name='luck',
        ),
    ]
