# Generated by Django 3.0.8 on 2021-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0018_auto_20201225_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='luck',
            new_name='luck8414',
        ),
    ]
