# Generated by Django 3.0.8 on 2021-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0019_auto_20210104_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='trim_leverage_to',
            field=models.PositiveIntegerField(default=10, help_text='Trim leverage when create the Signal from SignalOrig'),
        ),
    ]
