# Generated by Django 3.0.8 on 2021-02-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0020_crontask_trim_leverage_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='allow_remove_tps_of_eps_for_first_formation',
            field=models.BooleanField(default=False, help_text='Take profits or EPs will be deleted one by one if balance is not enough to form Signal'),
        ),
    ]
