# Generated by Django 3.0.8 on 2021-02-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0021_crontask_allow_remove_tps_of_eps_for_first_formation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='klondike',
            new_name='klondike_margin',
        ),
    ]
