# Generated by Django 3.0.8 on 2021-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0022_auto_20210209_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='klondike_scalp',
            field=models.BooleanField(default=False),
        ),
    ]
