# Generated by Django 3.0.8 on 2021-02-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0023_crontask_klondike_scalp'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='klondike_altcoin',
            field=models.BooleanField(default=False),
        ),
    ]
