# Generated by Django 3.0.8 on 2021-02-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0024_crontask_klondike_altcoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontask',
            name='bull_exclusive',
        ),
        migrations.RemoveField(
            model_name='crontask',
            name='crypto_zone',
        ),
        migrations.RemoveField(
            model_name='crontask',
            name='raticoin',
        ),
        migrations.RemoveField(
            model_name='crontask',
            name='simple_future',
        ),
    ]
