# Generated by Django 3.0.8 on 2021-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0025_auto_20210225_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='crypto_futures',
            field=models.BooleanField(default=False),
        ),
    ]
