# Generated by Django 3.0.8 on 2021-03-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0026_crontask_crypto_futures'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='do_not_create_if_symbol_already_started',
            field=models.BooleanField(default=True, help_text='Do not create Signal if there is started one with this symbol'),
        ),
    ]
