# Generated by Django 3.0.8 on 2021-03-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0027_crontask_do_not_create_if_symbol_already_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='fsvzo',
            field=models.BooleanField(default=False),
        ),
    ]
