# Generated by Django 3.0.8 on 2021-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0028_crontask_fsvzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='do_not_create_opposite_position_to_a_started_one',
            field=models.BooleanField(default=True, help_text='Do not create Signal if there is started one with opposite direction'),
        ),
        migrations.AlterField(
            model_name='crontask',
            name='do_not_create_if_symbol_already_started',
            field=models.BooleanField(default=False, help_text='Do not create Signal both similar or opposite direction if there is started one with this symbol'),
        ),
    ]
