# Generated by Django 3.0.8 on 2021-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0029_auto_20210428_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='ai_se',
            field=models.BooleanField(default=False),
        ),
    ]
