# Generated by Django 3.0.8 on 2021-07-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0030_crontask_ai_se'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='allow_recreate_opposite_position',
            field=models.BooleanField(default=True, help_text='Allow closing signal and open a new one with opposite direction'),
        ),
    ]
