# Generated by Django 3.0.8 on 2021-11-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0032_crontask_see_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='see_result',
            new_name='current_balance',
        ),
    ]
