# Generated by Django 3.0.8 on 2022-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0032_crontask_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='vege_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crontask',
            name='slip_delta_sl_perc',
            field=models.FloatField(default=0.1, help_text='slip delta stop loss percentage'),
        ),
    ]
