# Generated by Django 3.0.8 on 2021-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0032_crontask_see_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='see_result',
            field=models.FloatField(default=0),
        ),
    ]
