# Generated by Django 3.0.8 on 2021-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0033_auto_20211122_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='see_result',
            field=models.FloatField(default=100),
        ),
    ]
