# Generated by Django 3.0.8 on 2021-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0035_auto_20211122_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='see_result',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
