# Generated by Django 3.0.8 on 2021-11-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0036_auto_20211122_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='see_result',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
