# Generated by Django 3.0.8 on 2021-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontask', '0037_auto_20211122_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='see_result',
            field=models.FloatField(default=0),
        ),
    ]
